/**
 * Extra translations for exotic converter categories.
 *
 * These names get merged into the main converter dictionary at runtime.
 * Keeps the original dictionaries.ts unchanged — just import this once
 * in main.tsx after dictionaries.ts has loaded.
 */

import { registerConverterNames } from './dictionaries';
import type { Locale } from './index';

const C = (translations: Partial<Record<Locale, string>>) => translations;

registerConverterNames({
  density: C({ en: 'Density', ru: 'Плотность', uk: 'Густина', es: 'Densidad', de: 'Dichte', fr: 'Densité', zh: '密度', ja: '密度', pt: 'Densidade', it: 'Densità', pl: 'Gęstość' }),
  force: C({ en: 'Force', ru: 'Сила', uk: 'Сила', es: 'Fuerza', de: 'Kraft', fr: 'Force', zh: '力', ja: '力', pt: 'Força', it: 'Forza', pl: 'Siła' }),
  torque: C({ en: 'Torque', ru: 'Момент силы', uk: 'Момент сили', es: 'Par', de: 'Drehmoment', fr: 'Couple', zh: '扭矩', ja: 'トルク', pt: 'Torque', it: 'Coppia', pl: 'Moment siły' }),
  illuminance: C({ en: 'Illuminance', ru: 'Освещённость', uk: 'Освітленість', es: 'Iluminancia', de: 'Beleuchtungsstärke', fr: 'Éclairement', zh: '照度', ja: '照度', pt: 'Iluminância', it: 'Illuminamento', pl: 'Natężenie oświetlenia' }),
  'luminous-flux': C({ en: 'Luminous flux', ru: 'Световой поток', uk: 'Світловий потік', es: 'Flujo luminoso', de: 'Lichtstrom', fr: 'Flux lumineux', zh: '光通量', ja: '光束', pt: 'Fluxo luminoso', it: 'Flusso luminoso', pl: 'Strumień świetlny' }),
  'magnetic-flux-density': C({ en: 'Magnetic flux density', ru: 'Магнитная индукция', uk: 'Магнітна індукція', es: 'Densidad de flujo magnético', de: 'Magnetische Flussdichte', fr: 'Densité de flux magnétique', zh: '磁通密度', ja: '磁束密度', pt: 'Densidade de fluxo magnético', it: 'Densità di flusso magnetico', pl: 'Indukcja magnetyczna' }),
  'magnetic-flux': C({ en: 'Magnetic flux', ru: 'Магнитный поток', uk: 'Магнітний потік', es: 'Flujo magnético', de: 'Magnetischer Fluss', fr: 'Flux magnétique', zh: '磁通量', ja: '磁束', pt: 'Fluxo magnético', it: 'Flusso magnetico', pl: 'Strumień magnetyczny' }),
  'flow-rate': C({ en: 'Flow rate', ru: 'Расход', uk: 'Витрата', es: 'Caudal', de: 'Volumenstrom', fr: 'Débit', zh: '流量', ja: '流量', pt: 'Vazão', it: 'Portata', pl: 'Natężenie przepływu' }),
  'music-intervals': C({ en: 'Music intervals', ru: 'Музыкальные интервалы', uk: 'Музичні інтервали', es: 'Intervalos musicales', de: 'Musikintervalle', fr: 'Intervalles musicaux', zh: '音程', ja: '音程', pt: 'Intervalos musicais', it: 'Intervalli musicali', pl: 'Interwały muzyczne' }),
  'radiation-rate': C({ en: 'Radiation dose rate', ru: 'Радиационный фон', uk: 'Радіаційний фон', es: 'Tasa de dosis radiactiva', de: 'Strahlungsdosisleistung', fr: 'Débit de dose', zh: '辐射剂量率', ja: '線量率', pt: 'Taxa de dose de radiação', it: 'Rateo di dose', pl: 'Moc dawki promieniowania' }),
  carbon: C({ en: 'Carbon footprint', ru: 'Углеродный след', uk: 'Вуглецевий слід', es: 'Huella de carbono', de: 'CO₂-Fußabdruck', fr: 'Empreinte carbone', zh: '碳足迹', ja: 'カーボンフットプリント', pt: 'Pegada de carbono', it: 'Impronta di carbonio', pl: 'Ślad węglowy' }),
  cooking: C({ en: 'Cooking measures', ru: 'Кулинарные меры', uk: 'Кулінарні міри', es: 'Medidas de cocina', de: 'Kochmaße', fr: 'Mesures culinaires', zh: '烹饪量', ja: '料理計量', pt: 'Medidas culinárias', it: 'Misure culinarie', pl: 'Miary kuchenne' }),
  alcohol: C({ en: 'Alcohol units', ru: 'Алкоголь', uk: 'Алкоголь', es: 'Unidades de alcohol', de: 'Alkoholeinheiten', fr: "Unités d'alcool", zh: '酒精单位', ja: 'アルコール単位', pt: 'Unidades de álcool', it: 'Unità alcoliche', pl: 'Jednostki alkoholu' }),
  'typing-speed': C({ en: 'Typing speed', ru: 'Скорость печати', uk: 'Швидкість друку', es: 'Velocidad de escritura', de: 'Schreibgeschwindigkeit', fr: 'Vitesse de frappe', zh: '打字速度', ja: 'タイピング速度', pt: 'Velocidade de digitação', it: 'Velocità di battitura', pl: 'Szybkość pisania' }),
  'cosmic-mass': C({ en: 'Cosmic masses', ru: 'Космические массы', uk: 'Космічні маси', es: 'Masas cósmicas', de: 'Kosmische Massen', fr: 'Masses cosmiques', zh: '宇宙质量', ja: '宇宙の質量', pt: 'Massas cósmicas', it: 'Masse cosmiche', pl: 'Masy kosmiczne' }),
  'cosmic-radius': C({ en: 'Cosmic radii', ru: 'Космические радиусы', uk: 'Космічні радіуси', es: 'Radios cósmicos', de: 'Kosmische Radien', fr: 'Rayons cosmiques', zh: '宇宙半径', ja: '宇宙の半径', pt: 'Raios cósmicos', it: 'Raggi cosmici', pl: 'Promienie kosmiczne' }),
  latency: C({ en: 'Latency', ru: 'Латентность', uk: 'Латентність', es: 'Latencia', de: 'Latenz', fr: 'Latence', zh: '延迟', ja: 'レイテンシ', pt: 'Latência', it: 'Latenza', pl: 'Opóźnienie' }),
  'pixel-density': C({ en: 'Pixel density', ru: 'Плотность пикселей', uk: 'Щільність пікселів', es: 'Densidad de píxeles', de: 'Pixeldichte', fr: 'Densité de pixels', zh: '像素密度', ja: 'ピクセル密度', pt: 'Densidade de pixels', it: 'Densità di pixel', pl: 'Gęstość pikseli' }),
  'purchasing-power': C({ en: 'Purchasing power', ru: 'Покупательная способность', uk: 'Купівельна спроможність', es: 'Poder adquisitivo', de: 'Kaufkraft', fr: "Pouvoir d'achat", zh: '购买力', ja: '購買力', pt: 'Poder de compra', it: "Potere d'acquisto", pl: 'Siła nabywcza' }),
  // Historical & cultural
  'old-russian-length': C({ en: 'Old Russian (length)', ru: 'Древнерусские меры (длина)', uk: 'Давньоруські міри (довжина)', es: 'Medidas rusas antiguas (longitud)', de: 'Altrussische Maße (Länge)', fr: 'Mesures russes anciennes (longueur)', zh: '古俄罗斯单位（长度）', ja: '古ロシアの単位（長さ）', pt: 'Medidas russas antigas (comprimento)', it: 'Misure russe antiche (lunghezza)', pl: 'Staroruskie miary (długość)' }),
  'old-russian-mass': C({ en: 'Old Russian (mass)', ru: 'Древнерусские меры (масса)', uk: 'Давньоруські міри (маса)', es: 'Medidas rusas antiguas (masa)', de: 'Altrussische Maße (Masse)', fr: 'Mesures russes anciennes (masse)', zh: '古俄罗斯单位（质量）', ja: '古ロシアの単位（質量）', pt: 'Medidas russas antigas (massa)', it: 'Misure russe antiche (massa)', pl: 'Staroruskie miary (masa)' }),
  'old-russian-volume': C({ en: 'Old Russian (volume)', ru: 'Древнерусские меры (объём)', uk: 'Давньоруські міри (об’єм)', es: 'Medidas rusas antiguas (volumen)', de: 'Altrussische Maße (Volumen)', fr: 'Mesures russes anciennes (volume)', zh: '古俄罗斯单位（体积）', ja: '古ロシアの単位（体積）', pt: 'Medidas russas antigas (volume)', it: 'Misure russe antiche (volume)', pl: 'Staroruskie miary (objętość)' }),
  'japanese-length': C({ en: 'Japanese (length)', ru: 'Японские меры (длина)', uk: 'Японські міри (довжина)', es: 'Medidas japonesas (longitud)', de: 'Japanische Maße (Länge)', fr: 'Mesures japonaises (longueur)', zh: '日本单位（长度）', ja: '尺貫法（長さ）', pt: 'Medidas japonesas (comprimento)', it: 'Misure giapponesi (lunghezza)', pl: 'Miary japońskie (długość)' }),
  'japanese-mass': C({ en: 'Japanese (mass)', ru: 'Японские меры (масса)', uk: 'Японські міри (маса)', es: 'Medidas japonesas (masa)', de: 'Japanische Maße (Masse)', fr: 'Mesures japonaises (masse)', zh: '日本单位（质量）', ja: '尺貫法（質量）', pt: 'Medidas japonesas (massa)', it: 'Misure giapponesi (massa)', pl: 'Miary japońskie (masa)' }),
  'japanese-volume': C({ en: 'Japanese (volume)', ru: 'Японские меры (объём)', uk: 'Японські міри (об’єм)', es: 'Medidas japonesas (volumen)', de: 'Japanische Maße (Volumen)', fr: 'Mesures japonaises (volume)', zh: '日本单位（体积）', ja: '尺貫法（体積）', pt: 'Medidas japonesas (volume)', it: 'Misure giapponesi (volume)', pl: 'Miary japońskie (objętość)' }),
  'japanese-area': C({ en: 'Japanese (area)', ru: 'Японские меры (площадь)', uk: 'Японські міри (площа)', es: 'Medidas japonesas (área)', de: 'Japanische Maße (Fläche)', fr: 'Mesures japonaises (aire)', zh: '日本单位（面积）', ja: '尺貫法（面積）', pt: 'Medidas japonesas (área)', it: 'Misure giapponesi (area)', pl: 'Miary japońskie (powierzchnia)' }),
  'chinese-length': C({ en: 'Chinese (length)', ru: 'Китайские меры (длина)', uk: 'Китайські міри (довжина)', es: 'Medidas chinas (longitud)', de: 'Chinesische Maße (Länge)', fr: 'Mesures chinoises (longueur)', zh: '市制（长度）', ja: '中国の単位（長さ）', pt: 'Medidas chinesas (comprimento)', it: 'Misure cinesi (lunghezza)', pl: 'Miary chińskie (długość)' }),
  'chinese-mass': C({ en: 'Chinese (mass)', ru: 'Китайские меры (масса)', uk: 'Китайські міри (маса)', es: 'Medidas chinas (masa)', de: 'Chinesische Maße (Masse)', fr: 'Mesures chinoises (masse)', zh: '市制（质量）', ja: '中国の単位（質量）', pt: 'Medidas chinesas (massa)', it: 'Misure cinesi (massa)', pl: 'Miary chińskie (masa)' }),
  'chinese-area': C({ en: 'Chinese (area)', ru: 'Китайские меры (площадь)', uk: 'Китайські міри (площа)', es: 'Medidas chinas (área)', de: 'Chinesische Maße (Fläche)', fr: 'Mesures chinoises (aire)', zh: '市制（面积）', ja: '中国の単位（面積）', pt: 'Medidas chinesas (área)', it: 'Misure cinesi (area)', pl: 'Miary chińskie (powierzchnia)' }),
  'ancient-length': C({ en: 'Ancient measures (length)', ru: 'Античные меры (длина)', uk: 'Античні міри (довжина)', es: 'Medidas antiguas (longitud)', de: 'Antike Maße (Länge)', fr: 'Mesures antiques (longueur)', zh: '古代单位（长度）', ja: '古代の単位（長さ）', pt: 'Medidas antigas (comprimento)', it: 'Misure antiche (lunghezza)', pl: 'Miary antyczne (długość)' }),
  'ancient-mass': C({ en: 'Ancient measures (mass)', ru: 'Античные меры (масса)', uk: 'Античні міри (маса)', es: 'Medidas antiguas (masa)', de: 'Antike Maße (Masse)', fr: 'Mesures antiques (masse)', zh: '古代单位（质量）', ja: '古代の単位（質量）', pt: 'Medidas antigas (massa)', it: 'Misure antiche (massa)', pl: 'Miary antyczne (masa)' }),
  'wine-bottles': C({ en: 'Wine bottles', ru: 'Винные бутылки', uk: 'Винні пляшки', es: 'Botellas de vino', de: 'Weinflaschen', fr: 'Bouteilles de vin', zh: '葡萄酒瓶', ja: 'ワインボトル', pt: 'Garrafas de vinho', it: 'Bottiglie di vino', pl: 'Butelki wina' }),
  'paper-size': C({ en: 'Paper sizes', ru: 'Размеры бумаги', uk: 'Розміри паперу', es: 'Tamaños de papel', de: 'Papierformate', fr: 'Formats de papier', zh: '纸张尺寸', ja: '紙の規格', pt: 'Tamanhos de papel', it: 'Formati di carta', pl: 'Formaty papieru' }),
  'shoe-size-men': C({ en: 'Shoe sizes (men)', ru: 'Размеры обуви (м.)', uk: 'Розміри взуття (ч.)', es: 'Tallas de zapatos (h.)', de: 'Schuhgrößen (Herren)', fr: 'Pointures (hommes)', zh: '鞋码（男）', ja: '靴のサイズ（男性）', pt: 'Tamanhos de sapato (h.)', it: 'Numeri di scarpe (u.)', pl: 'Rozmiary butów (m.)' }),
  'ring-size': C({ en: 'Ring sizes', ru: 'Размеры колец', uk: 'Розміри каблучок', es: 'Tallas de anillos', de: 'Ringgrößen', fr: 'Tailles de bagues', zh: '戒指尺寸', ja: 'リングサイズ', pt: 'Tamanhos de anel', it: 'Misure di anelli', pl: 'Rozmiary pierścionków' }),
  'nature-speeds': C({ en: 'Speeds in nature', ru: 'Скорости в природе', uk: 'Швидкості в природі', es: 'Velocidades en la naturaleza', de: 'Geschwindigkeiten in der Natur', fr: 'Vitesses dans la nature', zh: '自然界的速度', ja: '自然界の速度', pt: 'Velocidades na natureza', it: 'Velocità in natura', pl: 'Prędkości w naturze' }),
});
